### ISSUE TITLE
problem with paths

### ISSUE THREAD

**Issue by kallan0802** [aminyazdanpanah/python-ffmpeg-video-streaming#1]
**Describe the bug**
Hi, great project you have here. 

I am however having a problem with paths. I am using a post request to kick off the hls stream. The problem I am having seems to be with white-space in the file path. i.e /path/to/file.mkv works perfectly however /path/to the/file of choice.mkv raises an ffmpeg runtime error that the path does not exist. (runtimeERROR: path /path/to does not exist) 

I believe this is due to the terminal commands for ffmpeg as if I call ffmpeg in the terminal using quotes around white-space parts i.e  /path/"to the"/"file of choice".mkv then the command works. 

I removed the path checks in the programme to test a quoted path and I still got the error, this time (runtimeERROR: path /path/"to the"/"file of choice".mkv doesnt exist).

I do not understand enough of the python code to dig deeper here. New to coding.

Ive tried the pathlib library to create pureWindows path before sending to the create hls stream but this didn't work either

I am sure there is a simple solution to this I am not seeing, but im just not sure. Id appreciate and help!

Thanks :)

**To Reproduce**
1. try to use a path with white-space
2. See error

**Expected behavior**
paths with white-space to work same as those without

**Local machine (please complete the following information):**
 - OS: Windows
 - FFMpeg 4.2.1

**Additional context**
I am sure there is a simple solution I am missing!

**Comment by aminyazdanpanah** [comment]
Thank you for the report and full description. I have just fixed [the bug](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming/commit/b5be382af5d76bbe90d3696ee5df2d3a03cb11a7) and now you should update the package:

``` bash
pip install --upgrade python-ffmpeg-video-streaming
```
