### ISSUE TITLE
Ability to use from Video Frames

### ISSUE THREAD

**Issue by Odianosen25** [aminyazdanpanah/python-ffmpeg-video-streaming#10]
**Is your feature request related to a problem? Please describe.**

I have a system whereby I use opencv to capture frames and process. I will like to make use of your code, to stream these frames using the HLS protocol to a remote device in real-time.

I think the process is to first figure out to write the video file in 10 seconds chucks to an iO buffer, and get your package to process from there. Will that be possible please?

**Describe alternatives you've considered**

Nope not considered anyone 

**Additional context**

**Comment by aminyazdanpanah** [comment]
Actually, FFmpeg supports the capturing frames(you do not have to use [OpenCV](https://opencv.org/)) and it does not matter what source you are going to utilize with FFmpeg (file, webcam/camera, or screen).

For example, the following command,  encode HLS format from the camera(or your webcam):

``` bash
ffmpeg -y -f vfwcap -i 0 -r 30 -c:v libx264 -s:v 640x360 -hls_flags delete_segments \
 -hls_list_size 10 -hls_time 5 -b:v 274k -b:a 63k \
 -hls_segment_filename path/to/file_%04d.ts path/to/file.m3u8
```

Unfortunately, I am not able to spend time on this project these days but I am going to rewrite this project and I will consider your feature request.

**Comment by Odianosen25** [comment]
Ok thanks very much @aminyazdanpanah for the response. I will use the command as given. Kind regards
