### ISSUE TITLE
Issue in uploading video to GCP bucket iteratively, contents of previous iteration are uploaded 

### ISSUE THREAD

**Issue by khiladipappu** [aminyazdanpanah/python-ffmpeg-video-streaming#101]
**Describe the bug**
I ran a for loop iterating over the videos in my GCP bucket and then transcoded it. But while uploading the files back to my bucket after transcoding the first video stream is getting uploaded again and again

**To Reproduce**
There are 51 videos in my bucket

```
gcs = GCS()
for i in range(1, 52):
    video_id = str(i)
    video = ffmpeg_streaming.input(gcs, bucket_name="xxxxxxxx", object_name=f"{video_id}.mp4")
    _360p  = Representation(Size(640,360), Bitrate(276 * 1024, 128 * 1024))
    _480p  = Representation(Size(854,480), Bitrate(750 * 1024, 192 * 1024))
    _720p  = Representation(Size(1280,720), Bitrate(2048 * 1024, 320 * 1024))
    hls = video.hls(Formats.h264(), hls_time=5)
    # hls.auto_generate_representations()
    hls.representations(_360p, _480p, _720p)
    save_to_gcs = CloudManager().add(gcs, bucket_name="xxxxxxxx", folder=f"{video_id}")
  
    hls.output(clouds=save_to_gcs, monitor=monitor)
```
In all the folders from video id 2 to 51 contents of 1.mp4 is being uploaded

**Expected behavior**
In all the folders from video id 2 to 51 contents of respective files should be uploaded

**Local machine (please complete the following information):**
 - OS: MacOS

**Comment by aminyazdanpanah** [comment]
I think I know what is the problem but I don't have any solution for now.
Try to do it async and await until each loop is done

BTW, thank you for the report.
I am going to refactor this library and I will consider your bug report
