### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by JavierSanchezCastro** [aminyazdanpanah/python-ffmpeg-video-streaming#102]
When I try to execute the easy example of output an m3u8 file I get this error (Ubuntu 22.04)

`ERROR:root:ffmpeg failed to execute command: b"ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers\n  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  libavutil      56. 70.100 / 56. 70.100\n  libavcodec     58.134.100 / 58.134.100\n  libavformat    58. 76.100 / 58. 76.100\n  libavdevice    58. 13.100 / 58. 13.100\n  libavfilter     7.110.100 /  7.110.100\n  libswscale      5.  9.100 /  5.  9.100\n  libswresample   3.  9.100 /  3.  9.100\n  libpostproc    55.  9.100 / 55.  9.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomavc1\n    creation_time   : 2021-04-19T07:40:19.000000Z\n  Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\n  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\n    Metadata:\n      creation_time   : 2021-04-19T07:40:19.000000Z\n      handler_name    : L-SMASH Video Handler\n      vendor_id       : [0][0][0][0]\n      encoder         : AVC Coding\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomavc1\n    creation_time   : 2021-04-19T07:40:19.000000Z\n  Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\n  Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\n    Metadata:\n      creation_time   : 2021-04-19T07:40:19.000000Z\n      handler_name    : L-SMASH Video Handler\n      vendor_id       : [0][0][0][0]\n      encoder         : AVC Coding\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':\n  Metadata:\n    major_brand     : mp42\n    minor_version   : 0\n    compatible_brands: mp42mp41isomavc1\n    creation_time   : 2021-04-19T07:40:19.000000Z\n  Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\n  Stream #2:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\n    Metadata:\n      creation_time   : 2021-04-19T07:40:19.000000Z\n      handler_name    : L-SMASH Video Handler\n      vendor_id       : [0][0][0][0]\n      encoder         : AVC Coding\nStream mapping:\n  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))\n  Stream #0:0 -> #1:0 (h264 (native) -> h264 (libx264))\n  Stream #0:0 -> #2:0 (h264 (native) -> h264 (libx264))\nPress [q] to stop, [?] for help\n[libx264 @ 0x559879941700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512\n[libx264 @ 0x559879941700] profile High, level 4.0, 4:2:0, 8-bit\n[libx264 @ 0x559879941700] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=5282 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\n[hls @ 0x55987989f700] Opening '/hls_1920p_init.mp4' for writing\n[hls @ 0x55987989f700] Failed to open segment 'hls_1920p_init.mp4'\nCould not write header for output file #0 (incorrect codec parameters ?): Permission denied\nError initializing output stream 0:0 -- \n[libx264 @ 0x559879941700] final ratefactor: 17.50\nConversion failed!\n"
Traceback (most recent call last):
  File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/./main.py", line 21, in <module>
    hls.output('hls.m3u8')
  File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 93, in output
    self.run(ffmpeg_bin, monitor, **options)
  File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 121, in run
    asyncio.run(self.async_run(ffmpeg_bin, monitor, **options))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 112, in async_run
    self._run(ffmpeg_bin, monitor, **options)
  File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 106, in _run
    self.pipe, err = process.run()
  File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_process.py", line 122, in run
    raise RuntimeError('ffmpeg failed to execute command: ', error)
RuntimeError: ('ffmpeg failed to execute command: ', 'b"ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers\\n  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)\\n  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\\n  libavutil      56. 70.100 / 56. 70.100\\n  libavcodec     58.134.100 / 58.134.100\\n  libavformat    58. 76.100 / 58. 76.100\\n  libavdevice    58. 13.100 / 58. 13.100\\n  libavfilter     7.110.100 /  7.110.100\\n  libswscale      5.  9.100 /  5.  9.100\\n  libswresample   3.  9.100 /  3.  9.100\\n  libpostproc    55.  9.100 / 55.  9.100\\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'video.mp4\':\\n  Metadata:\\n    major_brand     : mp42\\n    minor_version   : 0\\n    compatible_brands: mp42mp41isomavc1\\n    creation_time   : 2021-04-19T07:40:19.000000Z\\n  Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\\n  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\\n    Metadata:\\n      creation_time   : 2021-04-19T07:40:19.000000Z\\n      handler_name    : L-SMASH Video Handler\\n      vendor_id       : [0][0][0][0]\\n      encoder         : AVC Coding\\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from \'video.mp4\':\\n  Metadata:\\n    major_brand     : mp42\\n    minor_version   : 0\\n    compatible_brands: mp42mp41isomavc1\\n    creation_time   : 2021-04-19T07:40:19.000000Z\\n  Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\\n  Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\\n    Metadata:\\n      creation_time   : 2021-04-19T07:40:19.000000Z\\n      handler_name    : L-SMASH Video Handler\\n      vendor_id       : [0][0][0][0]\\n      encoder         : AVC Coding\\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from \'video.mp4\':\\n  Metadata:\\n    major_brand     : mp42\\n    minor_version   : 0\\n    compatible_brands: mp42mp41isomavc1\\n    creation_time   : 2021-04-19T07:40:19.000000Z\\n  Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\\n  Stream #2:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\\n    Metadata:\\n      creation_time   : 2021-04-19T07:40:19.000000Z\\n      handler_name    : L-SMASH Video Handler\\n      vendor_id       : [0][0][0][0]\\n      encoder         : AVC Coding\\nStream mapping:\\n  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))\\n  Stream #0:0 -> #1:0 (h264 (native) -> h264 (libx264))\\n  Stream #0:0 -> #2:0 (h264 (native) -> h264 (libx264))\\nPress [q] to stop, [?] for help\\n[libx264 @ 0x559879941700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512\\n[libx264 @ 0x559879941700] profile High, level 4.0, 4:2:0, 8-bit\\n[libx264 @ 0x559879941700] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=5282 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\\n[hls @ 0x55987989f700] Opening \'/hls_1920p_init.mp4\' for writing\\n[hls @ 0x55987989f700] Failed to open segment \'hls_1920p_init.mp4\'\\nCould not write header for output file #0 (incorrect codec parameters ?): Permission denied\\nError initializing output stream 0:0 -- \\n[libx264 @ 0x559879941700] final ratefactor: 17.50\\nConversion failed!\\n"')`

**Comment by hadpro24** [comment]
> When I try to execute the easy example of output an m3u8 file I get this error (Ubuntu 22.04)
> 
> `ERROR:root:ffmpeg failed to execute command: b"ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers\n built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)\n configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n libavutil 56. 70.100 / 56. 70.100\n libavcodec 58.134.100 / 58.134.100\n libavformat 58. 76.100 / 58. 76.100\n libavdevice 58. 13.100 / 58. 13.100\n libavfilter 7.110.100 / 7.110.100\n libswscale 5. 9.100 / 5. 9.100\n libswresample 3. 9.100 / 3. 9.100\n libpostproc 55. 9.100 / 55. 9.100\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':\n Metadata:\n major_brand : mp42\n minor_version : 0\n compatible_brands: mp42mp41isomavc1\n creation_time : 2021-04-19T07:40:19.000000Z\n Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\n Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\n Metadata:\n creation_time : 2021-04-19T07:40:19.000000Z\n handler_name : L-SMASH Video Handler\n vendor_id : [0][0][0][0]\n encoder : AVC Coding\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':\n Metadata:\n major_brand : mp42\n minor_version : 0\n compatible_brands: mp42mp41isomavc1\n creation_time : 2021-04-19T07:40:19.000000Z\n Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\n Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\n Metadata:\n creation_time : 2021-04-19T07:40:19.000000Z\n handler_name : L-SMASH Video Handler\n vendor_id : [0][0][0][0]\n encoder : AVC Coding\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':\n Metadata:\n major_brand : mp42\n minor_version : 0\n compatible_brands: mp42mp41isomavc1\n creation_time : 2021-04-19T07:40:19.000000Z\n Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\n Stream #2:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\n Metadata:\n creation_time : 2021-04-19T07:40:19.000000Z\n handler_name : L-SMASH Video Handler\n vendor_id : [0][0][0][0]\n encoder : AVC Coding\nStream mapping:\n Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))\n Stream #0:0 -> #1:0 (h264 (native) -> h264 (libx264))\n Stream #0:0 -> #2:0 (h264 (native) -> h264 (libx264))\nPress [q] to stop, [?] for help\n[libx264 @ 0x559879941700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512\n[libx264 @ 0x559879941700] profile High, level 4.0, 4:2:0, 8-bit\n[libx264 @ 0x559879941700] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=5282 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\n[hls @ 0x55987989f700] Opening '/hls_1920p_init.mp4' for writing\n[hls @ 0x55987989f700] Failed to open segment 'hls_1920p_init.mp4'\nCould not write header for output file #0 (incorrect codec parameters ?): Permission denied\nError initializing output stream 0:0 -- \n[libx264 @ 0x559879941700] final ratefactor: 17.50\nConversion failed!\n" Traceback (most recent call last): File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/./main.py", line 21, in <module> hls.output('hls.m3u8') File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 93, in output self.run(ffmpeg_bin, monitor, **options) File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 121, in run asyncio.run(self.async_run(ffmpeg_bin, monitor, **options)) File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete return future.result() File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 112, in async_run self._run(ffmpeg_bin, monitor, **options) File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_media.py", line 106, in _run self.pipe, err = process.run() File "/home/javier/Escritorio/EPITECH/TEK3/EIP/test_webcam2/env/lib/python3.10/site-packages/ffmpeg_streaming/_process.py", line 122, in run raise RuntimeError('ffmpeg failed to execute command: ', error) RuntimeError: ('ffmpeg failed to execute command: ', 'b"ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers\\n built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)\\n configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\\n libavutil 56. 70.100 / 56. 70.100\\n libavcodec 58.134.100 / 58.134.100\\n libavformat 58. 76.100 / 58. 76.100\\n libavdevice 58. 13.100 / 58. 13.100\\n libavfilter 7.110.100 / 7.110.100\\n libswscale 5. 9.100 / 5. 9.100\\n libswresample 3. 9.100 / 3. 9.100\\n libpostproc 55. 9.100 / 55. 9.100\\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'video.mp4\':\\n Metadata:\\n major_brand : mp42\\n minor_version : 0\\n compatible_brands: mp42mp41isomavc1\\n creation_time : 2021-04-19T07:40:19.000000Z\\n Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\\n Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\\n Metadata:\\n creation_time : 2021-04-19T07:40:19.000000Z\\n handler_name : L-SMASH Video Handler\\n vendor_id : [0][0][0][0]\\n encoder : AVC Coding\\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from \'video.mp4\':\\n Metadata:\\n major_brand : mp42\\n minor_version : 0\\n compatible_brands: mp42mp41isomavc1\\n creation_time : 2021-04-19T07:40:19.000000Z\\n Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\\n Stream #1:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\\n Metadata:\\n creation_time : 2021-04-19T07:40:19.000000Z\\n handler_name : L-SMASH Video Handler\\n vendor_id : [0][0][0][0]\\n encoder : AVC Coding\\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from \'video.mp4\':\\n Metadata:\\n major_brand : mp42\\n minor_version : 0\\n compatible_brands: mp42mp41isomavc1\\n creation_time : 2021-04-19T07:40:19.000000Z\\n Duration: 00:00:28.04, start: 0.000000, bitrate: 5411 kb/s\\n Stream #2:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1080x1920, 5408 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)\\n Metadata:\\n creation_time : 2021-04-19T07:40:19.000000Z\\n handler_name : L-SMASH Video Handler\\n vendor_id : [0][0][0][0]\\n encoder : AVC Coding\\nStream mapping:\\n Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))\\n Stream #0:0 -> #1:0 (h264 (native) -> h264 (libx264))\\n Stream #0:0 -> #2:0 (h264 (native) -> h264 (libx264))\\nPress [q] to stop, [?] for help\\n[libx264 @ 0x559879941700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512\\n[libx264 @ 0x559879941700] profile High, level 4.0, 4:2:0, 8-bit\\n[libx264 @ 0x559879941700] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=5282 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00\\n[hls @ 0x55987989f700] Opening \'/hls_1920p_init.mp4\' for writing\\n[hls @ 0x55987989f700] Failed to open segment \'hls_1920p_init.mp4\'\\nCould not write header for output file #0 (incorrect codec parameters ?): Permission denied\\nError initializing output stream 0:0 -- \\n[libx264 @ 0x559879941700] final ratefactor: 17.50\\nConversion failed!\\n"')`

I have the same problem -:)

**Comment by aminyazdanpanah** [comment]
@JavierSanchezCastro @hadpro24 
I can not help you with the little information you provided but according to your FFmpeg error log, it seems like the path you tried to save your files is incorrect, or you don't have permission to write in this path.

``` log
Failed to open segment 'hls_1920p_init.mp4'
Could not write header for output file
```

Try to use the full path (e.x. /var/www/media/mystream/hls.m3u8) and make sure FFmpeh has access to write in this directory

if you have any further problems, please post your code here
