### ISSUE TITLE
Encoding with AV1?

### ISSUE THREAD

**Issue by ryankashi** [aminyazdanpanah/python-ffmpeg-video-streaming#103]
Is there any way to select AV1 for my format?

When I try to encode my video using AV1, via:

`video.dash(Formats.AV1())`

I get an error.

Is AV1 supported with this package? Since it is built in to FFMPEG it should be supported

**Comment by aminyazdanpanah** [comment]
see #57 .
However, I am not sure if browsers support this codec.
