### ISSUE TITLE
how to make multiple representations for HLS stream while capturing webcam

### ISSUE THREAD

**Issue by 7luka7tadic7** [aminyazdanpanah/python-ffmpeg-video-streaming#108]
**Describe the bug**
I cannot make multiple representations for HLS stream while capturing webcam. When i try this code, it crashes.

**To Reproduce**
This is my code:
import ffmpeg_streaming
from ffmpeg_streaming import Formats,Bitrate, Representation, Size 

video = ffmpeg_streaming.input('Fantech Luminous C30', capture = True)

_360p  = Representation(Size(640, 360), Bitrate(276 * 1024, 128 * 1024))
_480p  = Representation(Size(854, 480), Bitrate(750 * 1024, 192 * 1024))
_720p  = Representation(Size(1280, 720), Bitrate(2048 * 1024, 320 * 1024))

hls = video.hls(Formats.h264(),hls_list_size=10, hls_time=5)
hls.flags('delete_segments')
hls.representations( _360p,_480p,_720p)
hls.output('C:\\Users\\ltadic\\Desktop\\camera_stream\\hls1.m3u8')

**Expected behavior**
hls.output() creates HLs stream with _360p, _480p and _720p quality

**Local machine (please complete the following information):**
 - OS: Windows or Linux
 - FFMpeg

**Comment by aminyazdanpanah** [comment]
Thank you for the report.
I am going to refactor this library and I will consider your bug report
