### ISSUE TITLE
Wrong aspect ratio when playing the resulting m3u8 file

### ISSUE THREAD

**Issue by ghost** [aminyazdanpanah/python-ffmpeg-video-streaming#109]
**Describe the bug**
The aspect ratio of the video when streaming the m3u8 file are not those of the original video. 

**To Reproduce**

1. pip install python-ffmpeg-video-streaming
2. `import ffmpeg_streaming

video = ffmpeg_streaming.input(path_to_original_video)

hls = video.hls(ffmpeg_streaming.Formats.h264())
hls.auto_generate_representations()
hls.output('hls.m3u8')`

**Expected behavior**
Accurate aspect ratio.

**Screenshots**
original video: https://ibb.co/1dBZggq
m3u8 result: https://ibb.co/mvNzrYK

**Local machine (please complete the following information):**
 - OS: OSX 13.1 
 - FFMped 5.1.2

UPDATE:
- this problem occurs when the video's rotation is portrait.

**Comment by aminyazdanpanah** [comment]
Thank you for the report.
I am going to refactor this library and I will consider your bug report
