### ISSUE TITLE
rtsp_transport with TCP

### ISSUE THREAD

**Issue by HuyAIHub** [aminyazdanpanah/python-ffmpeg-video-streaming#111]
**Big thanks to you**
This git repo helps me alot, thanks bro.

**how can I add rtsp_transport in this code**
but yesterday i tried with a rtsp which need use TCP protocol when reading rtsp stream.
i used these command and run it in commandline : " ffmpeg -rtsp_transport tcp -i "rtsp://x.x.x.x:554/user=x&password=x&channel=2&stream=0.sdp" -y video.jpg "
=> it works no mater

**but i need add '-rtsp_transport tcp' in your code in python. please give me a hand**

**Comment by aminyazdanpanah** [comment]
Try the following code:

``` python
 video = ffmpeg_streaming.input("rtsp://x.x.x.x:554/user=x&password=x&channel=2&stream=0.sdp", pre_opts={rtsp_transport: "tcp"})
```
