### ISSUE TITLE
 Create a socket connection and show a progress bar(or other parameters) to your users

### ISSUE THREAD

**Issue by Forchapeatl** [aminyazdanpanah/python-ffmpeg-video-streaming#113]
Please What django library should I install to enable socket show progress bar to users ?

**Comment by aminyazdanpanah** [comment]
It is up to you which Django library you want to use.
Personally, I use [Django Channels](https://channels.readthedocs.io/en/stable/deploying.html?highlight=websocket#http-and-websocket) and WebSocket. See this **[blog](https://blog.logrocket.com/django-channels-and-websockets/)** for an impression.
