### ISSUE TITLE
file saving in cloud

### ISSUE THREAD

**Issue by amirdks** [aminyazdanpanah/python-ffmpeg-video-streaming#119]
i want save generated files to aws cloud but after run code nothing save in my bucket :

> file = PrivateFile.objects.first()
>         s3 = S3(aws_access_key_id=settings.AWS_ACCESS_KEY_ID, endpoint_url=settings.AWS_S3_ENDPOINT_URL,
>                 aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY )
>         video = ffmpeg_streaming.input(s3, bucket_name="testforvideos", key="private/" + file.file.name)
>         hls = video.hls(Formats.h264())
>         hls.representations(self._360p, self._480p, self._720p)
>         save_to_s3 = CloudManager().add(s3, bucket_name="testforvideos", filename="hls.m3u8")
>         hls.output(clouds=save_to_s3, monitor=self.monitor)

what's the problem ?!

**Comment by L-U-C-K-Y** [comment]
I also encountered this issue, have you found a solution? @amirdks

**Comment by amirdks** [comment]
> I also encountered this issue, have you found a solution? @amirdks

yeah. you can first get your video from cloud storage with 'input' method and save theme in your server or local storage :

`s3 = S3(aws_access_key_id='YOUR_KEY_ID', aws_secret_access_key='YOUR_KEY_SECRET', region_name='YOUR_REGION')
video = ffmpeg_streaming.input(s3, bucket_name="bucket-name", key="video.mp4")
hls = video.hls(Formats.h264())
hls.auto_generate_representations()
hls.output('/var/media/hls.m3u8')`

After that take and upload the files one by one from the folder you saved them in and then delete the files from your local storage :

`video_files = [f for f in os.listdir('/var/media/') if isfile(join('/var/media/', f))]
        for file in video_files:
            bucket.upload_file('/var/media/' + file, "private/" + file,
                               settings.AWS_STORAGE_BUCKET_NAME)
            pathlib.Path('/var/media/' + file).unlink()`
