### ISSUE TITLE
HTTP PUT Method To Upload All The Segments Files To The HTTP Server.

### ISSUE THREAD

**Issue by ncrshubham** [aminyazdanpanah/python-ffmpeg-video-streaming#15]
First  of All Thank you @aminyazdanpanah  For This Library, This Works Fine For Saving Output To Local.

But I am Facing Some Issue In Saving output To Ftp Server and Using  The HTTP PUT Method To Upload All The Segments Files To The HTTP Server.

Also I Want to Know In The HLS Method, How To Create And Upload The Master Playlist To The Server Manually.

**Comment by aminyazdanpanah** [comment]
Thanks for the bug report(HLS content to a server). I will resolve it in the next release, but you can still upload all DASH files to remote resources using FTP protocol.

```python
def time_left(time_, total):
    if time_ != 0:
        diff_time = time.time() - start_time
        seconds_left = total * diff_time / time_ - diff_time
        time_left = str(datetime.timedelta(seconds=int(seconds_left))) + ' left'
    else:
        time_left = 'calculating...'

    return time_left


def monitor(ffmpeg, duration, time_):
    per = round(time_ / duration * 100)
    sys.stdout.write("\rTranscoding...(%s%%) %s [%s%s]" % (per, time_left(time_, duration), '#' * per, '-' * (100 - per)))
    sys.stdout.flush()


video = ffmpeg_streaming.input('path/to/video')

dash = video.dash(Formats.h264())
dash.auto_generate_representations()
dash.output('ftp://[user[:password]@]server[:port]/path/to/remote/resource.mpd', monitor=monitor)

```

**NOTE:** Refer to FFmpeg docs, FTP protocol can be used as an output, but it is recommended to not do it unless special care is taken (tests, customized server configuration, etc.). Different FTP servers behave in a different way during seek operation.

See **[FFmpeg FTP (File Transfer Protocol)](https://ffmpeg.org/ffmpeg-protocols.html#ftp) doc** for more information.

Alternatively, you can use a custom cloud to upload your HLS content files to a server using FTP protocol.

```python
from ffmpeg_streaming import Clouds

class FTP(Clouds):

    def upload_directory(self, directory, **options):
        # @TODO: upload a directory to a server using FTP protocol
        pass

    def download(self, filename=None, **options):
        # @TODO: download a file to a local path using FTP protocol
        pass

ftp = FTP()

save_to_ftp = CloudManager().add(ftp, options="value")

video = ffmpeg_streaming.input(ftp, options="value", options1="value1")

hls = video.hls(Formats.h264())
hls.auto_generate_representations()

hls.output(clouds=save_to_ftp)
```

**NOTE:** This option does not support live streaming(only [VOD](https://en.wikipedia.org/wiki/Video_on_demand))
