### ISSUE TITLE
Gpu acceleration 

### ISSUE THREAD

**Issue by 1h23** [aminyazdanpanah/python-ffmpeg-video-streaming#17]
Hi! 

Thanks a lot for your work! You saved a lot of time for our team. Please let me know if there any chance to use hardware acceleration like CUDA -hwaccel cuvid  -c:v h264_cuvid / AMD / Intel Quick Sync

**Comment by aminyazdanpanah** [comment]
Try the following code:

``` python
import datetime
import sys
import time

import ffmpeg_streaming
from ffmpeg_streaming import Formats


start_time = time.time()


def time_left(time_, total):
    if time_ != 0:
        diff_time = time.time() - start_time
        seconds_left = total * diff_time / time_ - diff_time
        time_left = str(datetime.timedelta(seconds=int(seconds_left))) + ' left'
    else:
        time_left = 'calculating...'

    return time_left


def monitor(ffmpeg, duration, time_, process):
    # You can update a field in your database or log it to a file
    # You can also create a socket connection and show a progress bar to users
    # logging.info(ffmpeg) or print(ffmpeg)

    # if "something happened":
    #     process.terminate()

    per = round(time_ / duration * 100)
    sys.stdout.write("\rTranscoding...(%s%%) %s [%s%s]" % (per, time_left(time_, duration), '#' * per, '-' * (100 - per)))
    sys.stdout.flush()

video = ffmpeg_streaming.input('/var/www/video.mp4')

hls = video.hls(Formats.h264('h264_cuvid'))
hls.auto_generate_representations()

hls.output('/var/media/hls.m3u8', monitor=monitor)
```

**Comment by 1h23** [comment]
I use Nvidia gtx 1080 max Q with CUDA 10

in this case I have error "unknown encoder \'h264_cuvid\'"

h264_cuvid is used only for decode video with -hwaccel cuvid

if I use CPU decoder and  h264_nvenc as gpu encoder - receive memory error "OpenEncodeSessionEx failed: out of memory(10)" 
this means that all Nvidia GPU (except Quadro series) have only 2-3 concurrent sessions and 2 nvenc working at the moment. 
[List here](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix)

**Also there are no chance to use software filters for scaling and pixel format(yuv420p only). Should use scale_cuda or scale_nnp(doesnt work for me)** 

_Here is working command WITHOUT MASTER.m3u8:_
`ffmpeg -hide_banner -y -vsync 0 -hwaccel cuvid -c:v h264_cuvid -i D:\001.mp4 –vf scale_cuda=640:360 -c:a aac -ar 48000 -c:v h264_nvenc -profile:v main -sc_threshold 0 -g 150 -keyint_min 48 -hls_time 10 -hls_playlist_type vod  -b:v 800k -maxrate 856k -b:a 96k -hls_segment_filename D:\001\360p_%03d.ts D:\001\360p.m3u8 –vf scale_cuda=842:480 -c:a aac -ar 48000 -c:v h264_nvenc -profile:v main -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -hls_playlist_type vod -b:v 1400k -maxrate 1498k -bufsize 2100k -b:a 128k -hls_segment_filename D:\001\480p_%03d.ts D:\001\480p.m3u8 –vf scale_cuda=1280:720 -c:a aac -ar 48000 -c:v h264_nvenc -profile:v main -sc_threshold 0 -g 48 -keyint_min 48 -hls_time 4 -hls_playlist_type vod -b:v 2800k -maxrate 2996k -bufsize 4200k -b:a 128k -hls_segment_filename D:\001\720p_%03d.ts D:\001\720p.m3u8`


_And cpu decoding with h264_nvenc encoder, generating  m3u8 masterfile:_
`ffmpeg  -vsync 1 -i D:\001.mp4 -vf yadif -b:v:0 5250k -c:v h264_nvenc -preset llhq -rc:v vbr_hq -pix_fmt yuv420p -profile:v main -level 4.1 -strict_gop 1 -rc-lookahead 32 -no-scenecut 1 -forced-idr 1 -b:v:1 4200k -c:v h264_nvenc -preset llhq -rc:v vbr_hq -pix_fmt yuv420p -profile:v main -level 4.1 -strict_gop 1 -rc-lookahead 32 -no-scenecut 1 -forced-idr 1 -b:v:1 3150k -c:v h264_nvenc -preset llhq -rc:v vbr_hq -pix_fmt yuv420p -profile:v main -level 4.1 -strict_gop 1 -rc-lookahead 32 -no-scenecut 1 -forced-idr 1 -b:a:0 256k -b:a:0 192k -b:a:0 128k -c:a aac -ar 48000  -map 0:v -map 0:a:0 -map 0:v -map 0:a:0 -map 0:v -map 0:a:0 -f hls -var_stream_map "v:0,a:0  v:1,a:1 v:2,a:2" -master_pl_name  master.m3u8 -t 300 -hls_time 10 -hls_init_time 4 -hls_list_size 10 -master_pl_publish_rate 10 -hls_flags delete_segments+discont_start+split_by_time vs%v\manifest.m3u8`

**Comment by aminyazdanpanah** [comment]
``` python
import datetime
import sys
import time

import ffmpeg_streaming
from ffmpeg_streaming import Formats


start_time = time.time()


def time_left(time_, total):
    if time_ != 0:
        diff_time = time.time() - start_time
        seconds_left = total * diff_time / time_ - diff_time
        time_left = str(datetime.timedelta(seconds=int(seconds_left))) + ' left'
    else:
        time_left = 'calculating...'

    return time_left


def monitor(ffmpeg, duration, time_, process):
    # You can update a field in your database or log it to a file
    # You can also create a socket connection and show a progress bar to users
    # logging.info(ffmpeg) or print(ffmpeg)

    # if "something happened":
    #     process.terminate()

    per = round(time_ / duration * 100)
    sys.stdout.write("\rTranscoding...(%s%%) %s [%s%s]" % (per, time_left(time_, duration), '#' * per, '-' * (100 - per)))
    sys.stdout.flush()
opts = {
    'hide_banner': None,
    'y': None,
    'vsync': 0,
    'hwaccel': 'cuvid',
    'c:v': 'h264_cuvid'
}

video = ffmpeg_streaming.input('/var/www/video.mp4', pre_opts=opts)

hls = video.hls(Formats.h264('h264_nvenc'))
hls.auto_generate_representations()

hls.output('/var/media/hls.m3u8', monitor=monitor)
```

Hope this works for you this time!
