### ISSUE TITLE
Specify additional output, e.g. Thumbnails / vtt sprite

### ISSUE THREAD

**Issue by Benny739** [aminyazdanpanah/python-ffmpeg-video-streaming#20]
Hi,

Is it possible to specify an additional output, e.g. for one or more Thumbnails?

**Comment by aminyazdanpanah** [comment]
The Thumbnails output(i.e. jpg, png, and etc) is not in the scope of this project but maybe I will create another project for this use case in the future.

**Comment by L-U-C-K-Y** [comment]
@aminyazdanpanah thanks a lot for this repo, do you have a suggestion, how we could extend this repo to add thumbnail generation?

Thanks
