### ISSUE TITLE
Add option to change hls_time for better scrubbing

### ISSUE THREAD

**Issue by ashish1405** [aminyazdanpanah/python-ffmpeg-video-streaming#24]
**Is your feature request related to a problem? Please describe.**
Currently when you scrub video in case of HLS, for e.g. in VLC, it gets scrubbed to nearest 10 sec segment. I checked the code and found that hls_time is set to 10 in `_command_builder.py`

**Describe the solution you'd like**
Probably the same way minrate/maxrate is set in Reprensentation

**Comment by aminyazdanpanah** [comment]
Try this:
``` python
hls = video.hls(Formats.h264(), hls_time=0)
```

**Comment by ashish1405** [comment]
Thanks @aminyazdanpanah

**Comment by gaurav1999** [comment]
what is hls_time = 0 meaning ? @aminyazdanpanah 
Can you please hint what will I need to do in order to break an mp4 to chunks of 7 seconds each ?

Thanks

**Comment by ashish1405** [comment]
@gaurav1999 , set hls_time to 7. This is for creating HLS ofcourse. MP4 chunks, I'm not exactly sure.
