### ISSUE TITLE
Broadcasting adaptive streaming Video to all the users

### ISSUE THREAD

**Issue by inf3cti0n95** [aminyazdanpanah/python-ffmpeg-video-streaming#26]
**Is your feature request related to a problem? Please describe.**
I am working on a personal project and I need a way to broadcast same stream to every user. But it should be an adaptive video. Can you please tell me how that can be achieved. 

For example - a video file played to all the users logged in everyone sees the same stream but adaptive. 

I know this does not come under this library. But, if you can point me to some right resources to do that

**Comment by aminyazdanpanah** [comment]
You can rebroadcast any stream using FFmpeg. Assuming your stream is `http://STREAM_DOMAIN.COM/PATH/To/LIVE/OR/ON/DEMAND/VIDEO `(you can also use other protocols such as RTMP, RTP and etc. See [FFmpeg Protocols Documentation](https://ffmpeg.org/ffmpeg-protocols.html) for more information ) and you will save your data in `/var/www/html/my_adptive_stream_directory` directory.
``` python 
import ffmpeg_streaming
from ffmpeg_streaming import Formats, Bitrate, Representation, Size

STREAM_URL= 'http://YOUR_DOMAIN.COM/PATH/To/LIVE/OR/ON/DEMAND/VIDEO'
OUTPUT = '/var/www/html/my_adptive_stream_directory/output.m3u8'

video = ffmpeg_streaming.input(STREAM_URL)

_360p  = Representation(Size(640, 360), Bitrate(276 * 1024, 128 * 1024))
_480p  = Representation(Size(854, 480), Bitrate(750 * 1024, 192 * 1024))
_720p  = Representation(Size(1280, 720), Bitrate(2048 * 1024, 320 * 1024))

hls = video.hls(Formats.h264())

hls = video.hls(Formats.h264(), hls_list_size=10, hls_time=5)
hls.flags('delete_segments')
hls.representations(_360p, _480p, _720p)
hls.output(OUTPUT)
```

Finally, you should pass a link of the master playlist to a player. For example:
http://YOUR_DOMAIN.COM/my_adptive_stream_directory/output.m3u8
