### ISSUE TITLE
Unable to upload generated mpd files to the cloud directly

### ISSUE THREAD

**Issue by csrujan** [aminyazdanpanah/python-ffmpeg-video-streaming#27]
from ffmpeg_streaming import GCS, CloudManager
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] ="storage.json"
gcs = GCS()

save_to_gcs = CloudManager().add(gcs, bucket_name="bucket-name")

video = ffmpeg_streaming.input("/var/media/video.mp4")

hls = video.hls(Formats.h264())
hls.auto_generate_representations()

hls.output(clouds=save_to_gcs)

<bold>**This is not working with all the access using storage.json**</bold>

**Comment by aminyazdanpanah** [comment]
What is the error message you get?
You can also add the following code to get more details(see streaming.log file):
``` python
import logging

logging.basicConfig(filename='streaming.log', level=logging.NOTSET, format='[%(asctime)s] %(levelname)s: %(message)s')
```
Note: Before posting your log here, make sure you **removed sensitive data** such as access token and passwords from the log.

**Comment by csrujan** [comment]
[2020-07-10 23:19:34,785] DEBUG: Using selector: SelectSelector
[2020-07-10 23:19:34,789] INFO: ffmpeg running command: ffmpeg -y -f dshow -i "video=Integrated Camera" -c:v libx264 -c:a aac -bf 1 -keyint_min 25 -g 250 -sc_threshold 40 -use_timeline 1 -use_template 1 -init_seg_name "video=Integrated Camera_init_$RepresentationID$.$ext$" -media_seg_name "video=Integrated Camera_chunk_$RepresentationID$_$Number%05d$.$ext$" -f dash -map 0 -s:v:0 640x360 -b:v:0 276k -b:a:0 128k -strict -2 "C:/Users/AppData/Local/Temp/ffmpeg_streaming_opk18hnh/video=Integrated Camera.mpd"

**Comment by aminyazdanpanah** [comment]
I just fixed the bug and now you should update the package. 

After updating the package, try the following code.

``` python
from ffmpeg_streaming import GCS, CloudManager, Formats

logging.basicConfig(filename='streaming.log', level=logging.NOTSET, format='[%(asctime)s] %(levelname)s: %(message)s')

# Create a service account key from here: https://console.cloud.google.com/apis/credentials/serviceaccountkey
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/var/keys/[YOUR-CREDENTIALS].json"
# if you are on windows, the path should be like: "C:\\User\\username\\Desktop\\[YOUR-CREDENTIALS].json"
gcs = GCS()

save_to_gcs = CloudManager().add(gcs, bucket_name="bucket_name", folder="folder/subfolder")

video = ffmpeg_streaming.input(gcs, bucket_name="bucket_name", object_name="video.mp4")
# you can also open a file from a local path
# video = ffmpeg_streaming.input("/var/media/video.mp4")

hls = video.hls(Formats.h264())
hls.auto_generate_representations()

hls.output(clouds=save_to_gcs)
# #  you can also pass a local path to save a copy of files to your server
```
Note-1: You should set an absolute path of credentials.json to your env. (you can create a service account key from here: https://console.cloud.google.com/apis/credentials/serviceaccountkey)
For example:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "C:\\User\\username\\Desktop\\storage.json"

Note-2: This option(saving files to clouds) does not support live streaming(only VOD). So you cannot open a resource from connected devices like your camera.
