### ISSUE TITLE
Audio is not getting recorded when using camera as input

### ISSUE THREAD

**Issue by csrujan** [aminyazdanpanah/python-ffmpeg-video-streaming#29]
i am able to record from camera and convert it to dash but audio is not getting recorded

**Comment by aminyazdanpanah** [comment]
If you are using Windows:
``` python
capture = ffmpeg_streaming.input('CAMERA NAME OR SCREEN NAME', audio='Microphone name here', capture=True)
```

If you browse the source code, you can find the answer to these types of questions.
