### ISSUE TITLE
How to install ffmpeg for docker?

### ISSUE THREAD

**Issue by pks9862728888** [aminyazdanpanah/python-ffmpeg-video-streaming#32]
Ffmpeg is a dependency of this package. So how to install ffmpeg in my python 3.7 docker conatiner?

**Comment by diegorosen** [comment]
@pks9862728888 In my case, using a docker image with _python3.8_ over _Linux alpine3.10_ (exactly this image: [tiangolo/uvicorn-gunicorn-fastapi:python3.8-alpine3.10](https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi))

I added this lines at Dockerfile to install ffmpeg:
```
RUN apk update
RUN apk add --no-cache ffmpeg
```
In case you are using Ubuntu for instance, you would do something like:
```
RUN apt update
RUN apt install ffmpeg
```

**Comment by pks9862728888** [comment]
@diegorosen Thank you very much. I have successfully installed the dependency in python:3.7-alpine image.

Just another off topic question. I have read a blogpost today which said using alpine images for production is not a good idea because it may lead to bugs. Is it true?

**Comment by diegorosen** [comment]
@pks9862728888 Don't really know, I've never used alpine for production. But to get an idea, [this DigitalOcean post](https://www.digitalocean.com/community/tutorials/how-to-optimize-docker-images-for-production#:~:text=Alpine%20is%20a%20suitable%20Linux,and%20better%20suited%20for%20production.) says alpine is suitable for production. Anyway, you could use an [ubuntu-minimal](https://ubuntu.com/blog/minimal-ubuntu-released) image instead

**Comment by pks9862728888** [comment]
@diegorosen Thank you for the help. Though I am using python:3.7-alpine image, yet I have a base image size of 726 MB. I will have to search for ways to decrease it further.
