### ISSUE TITLE
Stream to RTMP Server

### ISSUE THREAD

**Issue by hethcox** [aminyazdanpanah/python-ffmpeg-video-streaming#36]
I'm trying to send processed video frames to an nginx instance running the rtmp extension. From there the video is streamed to the clients. Is there a way write to an rtmp endpoint?

**Comment by aminyazdanpanah** [comment]
No, you can not write files to an RTMP endpoint using this library but you can use FFmpeg for this use case.

See the following page for more information about this protocol and examples:

https://ffmpeg.org/ffmpeg-protocols.html#rtmp
