### ISSUE TITLE
Sites that require a login

### ISSUE THREAD

**Issue by alefjim** [aminyazdanpanah/python-ffmpeg-video-streaming#37]
Hello Amin
Thanks for the article
I want to download a video from a site that, after logging in, has access to its HLS videos
How do I do the login steps in FFmpeg?

**Comment by aminyazdanpanah** [comment]
It depends on what is you mean by "logging in". If you mean FFmpeg can log in to a web form and fetch a video URL, I should say, it is not possible to do it using FFmpeg.
But if you mean FFmpeg can set some options such as `post_data`, `cookies` and etc to get a file, then you can do it.

See **[FFmpeg Protocols Documentation](https://ffmpeg.org/ffmpeg-protocols.html#http)** for more information
