### ISSUE TITLE
Provide feature to edit m4s video file

### ISSUE THREAD

**Issue by Vamsi-Rayapati** [aminyazdanpanah/python-ffmpeg-video-streaming#39]
I want to extract frames from m4s file and edit them before it send to client please respond quickly 

vamsi.rayapati444@gmail.com

**Comment by aminyazdanpanah** [comment]
Extracting a frame is not the scope of this project!

**Comment by Vamsi-Rayapati** [comment]
Can you give me information to how to do it

**Comment by aminyazdanpanah** [comment]
Run the following command in your terminal:

``` bash
ffmpeg -i path/to/video.mp4 -r 1/1 $filename%03d.jpg
```

see the link below for more information:
https://ffmpeg.org/ffmpeg-formats.html#image2-2
