### ISSUE TITLE
mpd streaming issue

### ISSUE THREAD

**Issue by Jayvagrawal** [aminyazdanpanah/python-ffmpeg-video-streaming#41]
After generating the dash playlist I am checking it for the list should play in all different versions. But it's playing only for top resolution. In my case, I have made it for _360p, _480p, _720p,_1080p but when I am accessing it through the master dash file so it's playing for only the 1080p version. A little help will be appreciated 

Thanks in advance.

**Comment by AlexxxMassyyy** [comment]
Great Python project! Thanks! But Same here. I try to throttle the network to "Slow 3G" and it still requests the highest quality possible. 

Info : 
- browser : Google Chrome and Mozilla
- server : python -m http.server 8000
- MediaPlayer : DashJS

I try both on Chrome and Mozilla -> same results
It requests directly the highest quality. (init_8 and init_9)

Is there something to change from the client side to make it auto ?

<img width="1430" alt="Screen2" src="https://user-images.githubusercontent.com/64650319/95116106-d0f8bf00-0746-11eb-8040-a10a94c0eb8e.png">




<img width="1073" alt="Screenshot" src="https://user-images.githubusercontent.com/64650319/95115144-4794bd00-0745-11eb-98ed-032fe9d8553f.png">

**Comment by Jayvagrawal** [comment]
> Great Python project! Thanks! But Same here. I try to throttle the network to "Slow 3G" and it still requests the highest quality possible.
> 
> Info :
> 
> * browser : Google Chrome and Mozilla
> * server : python -m http.server 8000
> * MediaPlayer : DashJS
> 
> I try both on Chrome and Mozilla -> same results
> It requests directly the highest quality. (init_8 and init_9)
> 
> Is there something to change from the client side to make it auto ?
> 
> <img alt="Screen2" width="1430" src="https://user-images.githubusercontent.com/64650319/95116106-d0f8bf00-0746-11eb-8040-a10a94c0eb8e.png">
> 
> <img alt="Screenshot" width="1073" src="https://user-images.githubusercontent.com/64650319/95115144-4794bd00-0745-11eb-98ed-032fe9d8553f.png">

if you just want to use dash only then it can be work with FFmpeg version 2.8. This issue will be solved in that version. But it creates the issue when you want HLS and DASH parallel.

**Comment by AlexxxMassyyy** [comment]
Hi, thanks for your answer. Yeah at the end I want to have HLS and DASH. My final project is to use "python-ffmpeg-video-streaming" to automatically transcode .mp4 video uploaded from the internet. And then being able to stream them on a web page. But for now I focused on DASH.

Sorry but I am new to transcoding and video format. I am using "ffmpeg version 4.3.1". In my understanding "python-ffmpeg-video-streaming" library calls "ffmpeg" to trancode the .mp4 video in DASH and HLS format (.mpd manifest and .m4s video chunk for DASH)

Then the DASHJS player, from the client-side, requests the needed information. And normally If the network speed is set to slow 3G, it should request a lower representation of the video and audio ("dash_chuck_3_xxxxx.m4s" chunk for example). But in my tests, it requests always the highest quality, and that makes it so long to download. Is there a mistake in the .mpd manifest or am I doing something wrong on client-side (DASHJS) ?

So you say "it can be work with FFmpeg version 2.8". But I am already using "ffmpeg version 4.3.1"

Thanks in advance.

**Comment by AlexxxMassyyy** [comment]
OK so for me the issue was the media player. I switch to Shaka-Player and it now works perfectly. Requesting lower quality chunk when bandwidth drops. 

<img width="1427" alt="shaka" src="https://user-images.githubusercontent.com/64650319/95621844-abcfbd80-0a72-11eb-9400-e559d8be50f8.png">

**Comment by aminyazdanpanah** [comment]
@Jayvagrawal Please post your code and your manifests content(HLS and DASH) here.

**Comment by Jayvagrawal** [comment]
> @Jayvagrawal Please post your code and your manifests content(HLS and DASH) here.

Hi, @aminyazdanpanah Thanks for your reply.

I am using these four lines of code for dash creation. 

video = ffmpeg_streaming.input(video_filel)
dash = video.dash(Formats.h264())
dash.auto_generate_representations()
dash.output(dash_output_path) 

Output video link after uploading it on the cloud. 
[https://toch-mumbai.s3.ap-south-1.amazonaws.com/sample/2020-10-01/dash_f_4.1.4+/index.mpd]
As you play this link so it will be work only for 1080p. 

HLS is working properly. Only having an issue in the DASH creation. 

Thanks!

**Comment by aminyazdanpanah** [comment]
It seems like your FFmpeg version is out of date. Make sure you have the latest version of FFmpeg on your machine.

How to get FFmpeg version:

``` bash
ffmpeg -version
```

Download the latest version(v 4.3):
https://ffmpeg.org/download.html
