### ISSUE TITLE
CMAF support

### ISSUE THREAD

**Issue by swagato-c** [aminyazdanpanah/python-ffmpeg-video-streaming#44]
**Is your feature request related to a problem? Please describe.**
CMAF is a newer packaging method that claims to save server space by half and provide low latency. 
Here's a description of the [same](https://www.ubik-ingenierie.com/blog/video-streaming-cmaf-and-low-latency/).
It seems FFMPEG also supports this. However, I am absolutely unaware of the switches to be used to make things work.

**Describe the solution you'd like**
methods to have cmaf support

**Comment by mojtaba-arvin** [comment]
Hi, to *fragmented MP4* segment type, you can call `fragmented_mp4()` of `HLS` class.
[see the example](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming/blob/cd214a1dd60338c427d7aa8fea17bc4bb670f7ad/examples/hls.py#L97)
The method will add `-hls_segment_type fmp4` flag as a option to the FFmpeg command.
Good luck

**Comment by aminyazdanpanah** [comment]
I am not sure FFmpeg supports the CMAF approach but you can set the hls_playlist option to 1 and the seg_duration  option to '.5' to generate `dash` and `hls` playlist files and also create fragmented mp4 files.


```python
dash = video.dash(Formats.h264(), hls_playlist=1, seg_duration='.5')
dash.auto_generate_representations()
dash.output('/var/media/dash.mpd')
```

You can also use @mojtaba-arvin's solution.

See [Dash options](https://ffmpeg.org/ffmpeg-formats.html#dash-2) for more information.
