### ISSUE TITLE
MKV to HLS has no audio

### ISSUE THREAD

**Issue by khoazero123** [aminyazdanpanah/python-ffmpeg-video-streaming#45]
I use the example code in file `examples\hls.py` to process convert `MKV` file to `HLS`. Then I use video.js to play video but fail.
I try to play via VLC has the same issue. (still has video)

Here in the error log in the browser console:
```
video.js:84 VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) audio append of 979216b failed for segment #0 in playlist 0-http://localhost:5000/test3/filename_1080p.m3u8
```
Origin MKV file:
![image](https://user-images.githubusercontent.com/2802354/100968973-eb8fbe80-3564-11eb-9bf5-04b8548f0402.png)

After convert to HLS:
![image](https://user-images.githubusercontent.com/2802354/100968911-cef38680-3564-11eb-91d9-a9d73a591797.png)

**Comment by aminyazdanpanah** [comment]
Try to set the audio codec to `AAC` and re-run the code. Maybe some browsers do not support ADTS audio codec.
