### ISSUE TITLE
can not read mp4 file from s3 bucket

### ISSUE THREAD

**Issue by amanbabbar-kipl** [aminyazdanpanah/python-ffmpeg-video-streaming#49]
I am following this link https://video.aminyazdanpanah.com/python/start/clouds?r=save
 with s3 bucket but ffmpeg can't read file from bucket and no error throw. i can read/put file on s3 with boto3 but not working with ffmpeg.

also when i did not pass bucket name, access key no error throw by ffmpeg.

**Comment by amanbabbar-kipl** [comment]
did anyone use this library for HLS with aws lambda?

**Comment by aminyazdanpanah** [comment]
I will check this issue later

**Comment by ShakeelAhmad-dev** [comment]
any update ?

**Comment by aminyazdanpanah** [comment]
Please Update the package:

``` python
pip install --upgrade python-ffmpeg-video-streaming
```
