### ISSUE TITLE
How to pass a main argument like "stream_loop" for hls

### ISSUE THREAD

**Issue by Nijinsha** [aminyazdanpanah/python-ffmpeg-video-streaming#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aminyazdanpanah** [comment]
I do not have any clue what is "stream_loop" and what you want to do. Please provide more information about your question by adding examples and minimal codes.
