### ISSUE TITLE
custom video representations

### ISSUE THREAD

**Issue by markmenezesmm** [aminyazdanpanah/python-ffmpeg-video-streaming#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by markmenezesmm** [comment]
Hie,
is there a way to add custom video representation....suppose i want my videos to be encoded using CRF(constant rate factor)...how do i do that?

**Comment by aminyazdanpanah** [comment]
You can specify representations using the `Representation` object and pass pass them to the add_reperesentation() method.

See [samples](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming#dash) for more information
