### ISSUE TITLE
nConversation Faield

### ISSUE THREAD

**Issue by erfanshekari** [aminyazdanpanah/python-ffmpeg-video-streaming#52]
I got this error, tried different inputs but same issue

![streaming_error](https://user-images.githubusercontent.com/75634046/105568193-baee2900-5d4c-11eb-9802-2719fff591b5.PNG)

**Comment by mojtaba-arvin** [comment]
According to the screenshot, your output path is where you don't have the privilege to write the file in that path. change your output path or use `chmod` command to change the access permissions of the path, or ....

**Comment by aminyazdanpanah** [comment]
Use @mojtaba-arvin's solution.
Thank you @mojtaba-arvin.
