### ISSUE TITLE
metadata not preserving

### ISSUE THREAD

**Issue by vijaykumarchettiar** [aminyazdanpanah/python-ffmpeg-video-streaming#56]
@aminyazdanpanah the meta data not preserving in the output as same as input. Is there any option to put -map_metadata 0 to copy global meta data details to any output.

**Comment by aminyazdanpanah** [comment]
See the link below
https://superuser.com/questions/996223/using-ffmpeg-to-copy-metadata-from-one-file-to-another

``` python
hls = video.hls(Formats.h264(), map_metadata=0, ...AND_OTHER_PARAMETER)
```
