### ISSUE TITLE
Big if `clouds` is a tuple (automatically throws a TypeError).

### ISSUE THREAD

**Issue by Syntactical01** [aminyazdanpanah/python-ffmpeg-video-streaming#6]
**Describe the bug**
Within `clouds.py` the following is a bug:
```
def save_to_clouds(clouds, dirname):
    if clouds is not None:
        if type(clouds) != list or type(clouds) != tuple:
            raise TypeError('Clouds must be type of list or tuple')
    ....
```
Note that if `clouds` is a `tuple` then the `TypeError` will be raised because it is not a `list`. `or` and `and` expressions short circuit in python so if the first expression is true it won't go to the next:
```
print(2 or 3) # Outputs 2
print(0 or 3 or 2) # Outputs 3
```
Similarly types should not be checked via `==`, `isinstance` if the preferred way to do it in python 🐍, but truly I just need this one spot fixed for my code to work in our docker containers.

Please change the above to:
```
def save_to_clouds(clouds, dirname):
    if clouds is not None:
        if not isinstance(clouds, (list, tuple)): # Tested in my fork
            raise TypeError('Clouds must be type of list or tuple')
    ....
```
Spent quite a few hours trying to figure out why my coding was failing even though I gave it a tuple :P.

**Comment by aminyazdanpanah** [comment]
Thank you for taking the time and effort in finding the bug. It seems like you fixed the bug. Would you like to submit the pull request(as you forked the repository and fixed it)? 

If not, it is okay, I will commit your code.

**Comment by Syntactical01** [comment]
To be honest I dont know how to that yet :P. I haven't worked with someone elses repo before.

**Comment by aminyazdanpanah** [comment]
I have just released a new version of the package and now you can update the package:
``` bash
pip install --upgrade python-ffmpeg-video-streaming
```
