### ISSUE TITLE
Question: are multiple audio streams and subtitles supportred?

### ISSUE THREAD

**Issue by venomone** [aminyazdanpanah/python-ffmpeg-video-streaming#60]
Hello,

most of my video files have multiple subtitles and audio streams. Is it possible to properly get them passed to a player using your lib. ? I was not able to find much onto this at the docs.

Kind regards and thanks in advance

**Comment by sannjayy** [comment]
I'm looking for the same .... If you get any solutions please let me know.  (https://codersbase.info/sannjayy/)

**Comment by aminyazdanpanah** [comment]
Unfortunately, no. Maybe I will add this feature later. #66
