### ISSUE TITLE
Why 1920p including as default?

### ISSUE THREAD

**Issue by tjikaljedy** [aminyazdanpanah/python-ffmpeg-video-streaming#64]
- OS: [bigsur 11.5.2 (20G95)]
 - FFMped [e.g. 4.1]
- BELANG.mp4 [ 1080 × 1920 ]
Hi Developers.

I realized while generate hls.m3u8 with as following:

video = ffmpeg_streaming.input('/Users/xxx/BELANG.mp4')
hls = video.hls(Formats.h264())
hls.auto_generate_representations([480])
hls.output('/Users/xxx/hls.m3u8')

the end results created 1920p file. My question how to disable this process or some bug occurs.

**Comment by aminyazdanpanah** [comment]
Try this:
``` python
video = ffmpeg_streaming.input('/Users/xxx/BELANG.mp4')
hls = video.hls(Formats.h264())
hls.auto_generate_representations([480], include_original=False)
hls.output('/Users/xxx/hls.m3u8')
```
