### ISSUE TITLE
getting error when convert video from mp4 to hls

### ISSUE THREAD

**Issue by ManojKumarMaurya** [aminyazdanpanah/python-ffmpeg-video-streaming#67]
**Describe the bug**

**To Reproduce**
from ffmpeg_streaming import Formats

hls = video.hls(Formats.h264())
hls.auto_generate_representations()
hls.output('/var/media/hls.m3u8')

**Expected behavior**
![Screenshot from 2021-09-06 23-11-46](https://user-images.githubusercontent.com/5546605/132249868-f89a86bf-e767-4317-bee1-c6cd754b0c3c.png)

**Screenshots**

**Local machine (please complete the following information):**
 - OS: [e.g. Linux]
 - FFMped [e.g. 4.1]

**Additional context**
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-48-94b42b7e9478> in <module>
      1 hls = video.hls(Formats.h264())
      2 hls.representations(_144p,_240p)
----> 3 hls.output('kls.m3u8')

~/.local/lib/python3.8/site-packages/ffmpeg_streaming/_media.py in output(self, output, clouds, run_command, ffmpeg_bin, monitor, **options)
     91 
     92         if run_command:
---> 93             self.run(ffmpeg_bin, monitor, **options)
     94 
     95     def probe(self, ffprobe_bin='ffprobe') -> FFProbe:

~/.local/lib/python3.8/site-packages/ffmpeg_streaming/_media.py in run(self, ffmpeg_bin, monitor, **options)
    119 
    120         if async_run:
--> 121             asyncio.run(self.async_run(ffmpeg_bin, monitor, **options))
    122         else:
    123             self._run(ffmpeg_bin, monitor, **options)

/usr/lib/python3.8/asyncio/runners.py in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by aminyazdanpanah** [comment]
See #25.
