### ISSUE TITLE
HSL segment duration

### ISSUE THREAD

**Issue by tjikaljedy** [aminyazdanpanah/python-ffmpeg-video-streaming#69]
Hi  Amin,

I was wondering, how to bring 1st _0000 hls chunk file become small size instead  of :

#EXTM3U
#EXT-X-VERSION:7
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-MAP:URI="9550e373-95f3-4386-8cb4-3351dd75a656_480p_init.mp4"
#EXTINF:8.250000,
9550e373-95f3-4386-8cb4-3351dd75a656_480p_0000.m4s
#EXTINF:0.957000,
9550e373-95f3-4386-8cb4-3351dd75a656_480p_0001.m4s
#EXTINF:6.237000,
9550e373-95f3-4386-8cb4-3351dd75a656_480p_0002.m4s
#EXT-X-ENDLIST

as you can see at first is ready big  size

Thx

**Comment by aminyazdanpanah** [comment]
Use `hls_time` kwarg:
``` python
hls = video.hls(Formats.h264(),  hls_time=5)
```

See #24
