### ISSUE TITLE
Getting Name Error for "ffmpeg_streaming"

### ISSUE THREAD

**Issue by ameyjir** [aminyazdanpanah/python-ffmpeg-video-streaming#70]
### Getting a Name Error 

`NameError: name 'ffmpeg_streaming' is not defined`

![image](https://user-images.githubusercontent.com/52775274/147545419-5ed7ca5b-9955-4968-bb6f-9aee79200d9f.png)

Obviously I have installed ffmpeg and python-ffmpeg-video-streaming

![image](https://user-images.githubusercontent.com/52775274/147545669-62eec797-e782-43a6-9995-d4519452527c.png)

I also tried it on a Ubuntu Instance, still getting the same error.

**Comment by aminyazdanpanah** [comment]
Add `import ffmpeg_streaming` line at the begging of your code
