### ISSUE TITLE
Allow custom ffmpeg flag to be passed

### ISSUE THREAD

**Issue by vertigo65536** [aminyazdanpanah/python-ffmpeg-video-streaming#71]
Specifically the -re command in my context. I want to live stream a file, and have it synced up. However ffmpeg encodes the video faster than it is getting played. It would solve the issue if either a method to force read input at native framerate could be added, or allow me to add custom flags

**Comment by aminyazdanpanah** [comment]
You can pass any argument you want!
``` python
hls = video.hls(Formats.h264(), arg='value', arg2='value', ...)
```

You can also pass a flag using the [flags](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming/blob/b9cdd78a791ee7d4dca8091eb0aef7246d531dc0/ffmpeg_streaming/_media.py#L213)  method
