### ISSUE TITLE
hls_flags single_file

### ISSUE THREAD

**Issue by mnervik** [aminyazdanpanah/python-ffmpeg-video-streaming#78]
Is it possible to use `-hls_flags single_file` and not generating "%04d" at the end of the filename?

For *720p* and *hls.m3u8*
Current Behaveour `-hls_flags single file` creates `hls_720_%04d.ts`
Expected Bahaveour `-hls_flags single_file` should create `hls_720.ts`

For For *720p*,*480p* and *hls.m3u8*
Current Behaveour `-hls_flags single file` creates `hls_720_%04d.ts` and `hls_480_%04d.ts`
Expected Bahaveour `-hls_flags single_file` should create `hls_720.ts` and `hls_480.ts`

**Comment by aminyazdanpanah** [comment]
If you use `auto_generate_representations` method then you can not change `hls_segment_filename` option. But if you use Represnentain object then you are able to change this option:

``` python
from ffmpeg_streaming import Formats, Bitrate, Representation, Size

_360p  = Representation(Size(640, 360), Bitrate(276 * 1024, 128 * 1024), hls_segment_filename='hls_360.ts')
_480p  = Representation(Size(854, 480), Bitrate(750 * 1024, 192 * 1024), hls_segment_filename='hls_480.ts')
_720p  = Representation(Size(1280, 720), Bitrate(2048 * 1024, 320 * 1024), hls_segment_filename='hls_720.ts')

hls = video.hls(Formats.h264())
hls.representations(_360p, _480p, _720p)
hls.output('/var/media/hls.m3u8')
```
