### ISSUE TITLE
HLS TO HLS SHOWS VIDEO BY JUMPS

### ISSUE THREAD

**Issue by atzitiondev** [aminyazdanpanah/python-ffmpeg-video-streaming#80]
When using HLS and encoding with DRM to HLS the video jumps and does not appear smooth, what would be the correct configuration to encode an HLS?

**Comment by aminyazdanpanah** [comment]
It is your player issue. make sure you use the latest version of [hls.js](https://github.com/video-dev/hls.js/releases) on your website.
