### ISSUE TITLE
restream to video player, without output to file

### ISSUE THREAD

**Issue by supermario18b** [aminyazdanpanah/python-ffmpeg-video-streaming#82]
**Is your feature request related to a problem? Please describe.**
Is it possible to pass the output directly to the video player (actually a restream on the fly)? I mean without saving the output to a file.

**Comment by aminyazdanpanah** [comment]
Generally yes, you can. It depends on which proxy server you use and whether it supports video streaming.
For example, if you are using Nginx as a proxy server, see the following pages to learn how to do it.

Doc:  https://www.nginx.com/blog/video-streaming-for-remote-learning-with-nginx/
Video: https://www.youtube.com/watch?v=Js1OlvRNsdI
Code: https://github.com/outcast/live-streaming-demo

Dont forget that the output should be like this:
``` python
stream.output('PROTOCOL://DOMAIN/PATH_TO_STREAM/out.m3u8 or mpd')
```
