### ISSUE TITLE
How can I show the process bar on Django HTML?

### ISSUE THREAD

**Issue by sannjayy** [aminyazdanpanah/python-ffmpeg-video-streaming#83]
I have created an admin panel using Django and [python-ffmpeg-video-streaming] everything is good, but I want to show process bar on HTML code.  Can anyone help me on this case?

**Comment by aminyazdanpanah** [comment]
It is up to you which approach you want to choose. Personally, I prefer to use [Django Channels](https://github.com/django/channels) (WebSocket) in this use case to pass data to the front-end.

**Comment by Forchapeatl** [comment]
@sannjayy , any succes with the django channels ?
