### ISSUE TITLE
how to use h264_amf for hls 

### ISSUE THREAD

**Issue by fernandon00b** [aminyazdanpanah/python-ffmpeg-video-streaming#84]
hls = video.hls(Formats.h264('h264_amf'))
hls.encryption(save_to, url)
hls.auto_generate_representations()
hls.output('\\bernadeath\\hls.m3u8' )

ERROR 
RuntimeError: ('ffmpeg failed to execute command: ', 'b"ffmpeg version N-106830-gb980d9e8ec-20220508 Copyright (c) 2000-2022 the FFmpeg developers\\r\\n  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)\\r\\n  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220508\\r\\n  libavutil      57. 24.101 / 57. 24.101\\r\\n  libavcodec     59. 27.100 / 59. 27.100\\r\\n  libavformat    59. 23.100 / 59. 23.100\\r\\n  libavdevice    59.  6.100 / 59.  6.100\\r\\n  libavfilter     8. 38.100 /  8. 38.100\\r\\n  libswscale      6.  6.100 /  6.  6.100\\r\\n  libswresample   4.  6.100 /  4.  6.100\\r\\n  libpostproc    56.  5.100 / 56.  5.100\\r\\nInput #0, mov,mp4,m4a,3gp,3g2,mj2, from \'bernadeath_isback.mp4\':\\r\\n  Metadata:\\r\\n    major_brand     : isom\\r\\n    minor_version   : 512\\r\\n    compatible_brands: isomiso2avc1mp41\\r\\n    encoder         : Lavf58.46.101\\r\\n  Duration: 00:28:21.98, start: 0.000000, bitrate: 3533 kb/s\\r\\n  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3392 kb/s, 29.70 fps, 29.97 tbr, 90k tbn (default)\\r\\n    Metadata:\\r\\n      handler_name    : VideoHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\n  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 133 kb/s (default)\\r\\n    Metadata:\\r\\n      handler_name    : SoundHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\nInput #1, mov,mp4,m4a,3gp,3g2,mj2, from \'bernadeath_isback.mp4\':\\r\\n  Metadata:\\r\\n    major_brand     : isom\\r\\n    minor_version   : 512\\r\\n    compatible_brands: isomiso2avc1mp41\\r\\n    encoder         : Lavf58.46.101\\r\\n  Duration: 00:28:21.98, start: 0.000000, bitrate: 3533 kb/s\\r\\n  Stream #1:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3392 kb/s, 29.70 fps, 29.97 tbr, 90k tbn (default)\\r\\n    Metadata:\\r\\n      handler_name    : VideoHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\n  Stream #1:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 133 kb/s (default)\\r\\n    Metadata:\\r\\n      handler_name    : SoundHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\nInput #2, mov,mp4,m4a,3gp,3g2,mj2, from \'bernadeath_isback.mp4\':\\r\\n  Metadata:\\r\\n    major_brand     : isom\\r\\n    minor_version   : 512\\r\\n    compatible_brands: isomiso2avc1mp41\\r\\n    encoder         : Lavf58.46.101\\r\\n  Duration: 00:28:21.98, start: 0.000000, bitrate: 3533 kb/s\\r\\n  Stream #2:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3392 kb/s, 29.70 fps, 29.97 tbr, 90k tbn (default)\\r\\n    Metadata:\\r\\n      handler_name    : VideoHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\n  Stream #2:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 133 kb/s (default)\\r\\n    Metadata:\\r\\n      handler_name    : SoundHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\nInput #3, mov,mp4,m4a,3gp,3g2,mj2, from \'bernadeath_isback.mp4\':\\r\\n  Metadata:\\r\\n    major_brand     : isom\\r\\n    minor_version   : 512\\r\\n    compatible_brands: isomiso2avc1mp41\\r\\n    encoder         : Lavf58.46.101\\r\\n  Duration: 00:28:21.98, start: 0.000000, bitrate: 3533 kb/s\\r\\n  Stream #3:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3392 kb/s, 29.70 fps, 29.97 tbr, 90k tbn (default)\\r\\n    Metadata:\\r\\n      handler_name    : VideoHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\n  Stream #3:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 133 kb/s (default)\\r\\n    Metadata:\\r\\n      handler_name    : SoundHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\nInput #4, mov,mp4,m4a,3gp,3g2,mj2, from \'bernadeath_isback.mp4\':\\r\\n  Metadata:\\r\\n    major_brand     : isom\\r\\n    minor_version   : 512\\r\\n    compatible_brands: isomiso2avc1mp41\\r\\n    encoder         : Lavf58.46.101\\r\\n  Duration: 00:28:21.98, start: 0.000000, bitrate: 3533 kb/s\\r\\n  Stream #4:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3392 kb/s, 29.70 fps, 29.97 tbr, 90k tbn (default)\\r\\n    Metadata:\\r\\n      handler_name    : VideoHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\n  Stream #4:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 133 kb/s (default)\\r\\n    Metadata:\\r\\n      handler_name    : SoundHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\nInput #5, mov,mp4,m4a,3gp,3g2,mj2, from \'bernadeath_isback.mp4\':\\r\\n  Metadata:\\r\\n    major_brand     : isom\\r\\n    minor_version   : 512\\r\\n    compatible_brands: isomiso2avc1mp41\\r\\n    encoder         : Lavf58.46.101\\r\\n  Duration: 00:28:21.98, start: 0.000000, bitrate: 3533 kb/s\\r\\n  Stream #5:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3392 kb/s, 29.70 fps, 29.97 tbr, 90k tbn (default)\\r\\n    Metadata:\\r\\n      handler_name    : VideoHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\n  Stream #5:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 133 kb/s (default)\\r\\n    Metadata:\\r\\n      handler_name    : SoundHandler\\r\\n      vendor_id       : [0][0][0][0]\\r\\n[NULL @ 0000026c2d9bdac0] Unable to find a suitable output format for \'aac\'\\r\\naac: Invalid argument\\r\\n"')

**Comment by aminyazdanpanah** [comment]
Your hardware must support this option. As I don’t have an AMD GPU, I can not help you in this case.
