### ISSUE TITLE
Is anyone using this tool as an NVR?

### ISSUE THREAD

**Issue by SeaDude** [aminyazdanpanah/python-ffmpeg-video-streaming#85]
Hello,

I *think* this tool could be used as a Network Video Recorder (NVR) for IP cameras and such.

1. Do you know of anyone using it as such?
2. Are there any examples you could point me to?

Thank you

**Comment by aminyazdanpanah** [comment]
No this is not the library you are looking for. Maybe you can save data from IP cameras and restream it but this tool could not be used as an NVR. 

I suggest that you use an NVR library like [Frigate](https://github.com/blakeblackshear/frigate)
