### ISSUE TITLE
error: "gbk" "utf-8"

### ISSUE THREAD

**Issue by dupenf** [aminyazdanpanah/python-ffmpeg-video-streaming#87]
File "D:\Program Files\python\lib\site-packages\ffmpeg_streaming\ffprobe.py", line 117, in save_as_json
    probe.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\ufffd' in position 3436: illegal multibyte sequence

how to solve it?

**Comment by dupenf** [comment]
def save_as_json(self, path):
        """
        @TODO: add documentation
        """
        with open(path, 'w') as probe:
            probe.write(self.out.decode('utf-8'))

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I have just fixed the bug in [https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming/commit/7b0ab4a918725a515c0b13934a5d85d759267eef](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming/commit/7b0ab4a918725a515c0b13934a5d85d759267eef)
