### ISSUE TITLE
.mpd files are not uploading to S3

### ISSUE THREAD

**Issue by pankaj-g10** [aminyazdanpanah/python-ffmpeg-video-streaming#93]
Chunks files are created and saved to s3 but cant see .mpd file in aws s3.
This is my code.
`
from settings_prod import AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME
import ffmpeg_streaming
from ffmpeg_streaming import Size, Bitrate, Representation, Formats, S3, CloudManager
class TestApiView(generics.GenericAPIView):

    def post(self, request):

        filename = 'S3 Object Path'

        s3 = S3(aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY, region_name='us-east-1')

        save_to_s3 = CloudManager(filename="Final_Video.mpd").add(
            s3, bucket_name=AWS_STORAGE_BUCKET_NAME, folder="streaming/ffmpeg1"
        )

        video = ffmpeg_streaming.input(s3, bucket_name=AWS_STORAGE_BUCKET_NAME, key=filename)

        _720p  = Representation(Size(1280, 720), Bitrate(276 * 1024, 128 * 1024))

        dash = video.dash(Formats.hevc())
        dash.representations(_720p)

        dash.output(clouds=save_to_s3)

        return `Response(status=status.HTTP_204_NO_CONTENT)``

**Comment by pankaj-g10** [comment]
Resolved

**Comment by aminyazdanpanah** [comment]
Good. I closed the issue because you found a solution
