### ISSUE TITLE
Unable to capture video/audio in Mac devices

### ISSUE THREAD

**Issue by Naveenkumar-Ragunathan** [aminyazdanpanah/python-ffmpeg-video-streaming#94]
**Describe the bug**
Unable to capture video/audio in Mac devices.

**To Reproduce**
1. Run the following snippet on Mac devices
```
from ffmpeg_streaming import Formats, input, Bitrate, Representation, Size

if __name__ == '__main__':
    video = input("0:0", capture=True)
    hls = video.hls(Formats.h264())
    _720p = Representation(Size(1280, 720), Bitrate(2048 * 1024, 320 * 1024))
    hls.representations(_720p)

    hls.output("hls.m3u8")
```
2. Error
```
RuntimeError: ('ffmpeg failed to execute command: ', "b'ffmpeg version 4.4.2 Copyright (c) 2000-2021 the FFmpeg developers\\n  built with clang version 13.0.1\\n  configuration: --prefix=/Users/runner/miniforge3/conda-bld/ffmpeg_1654969367107/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-demuxer=dash --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-libvpx --enable-pic --enable-pthreads --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libmp3lame --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1654969367107/_build_env/bin/pkg-config\\n  libavutil      56. 70.100 / 56. 70.100\\n  libavcodec     58.134.100 / 58.134.100\\n  libavformat    58. 76.100 / 58. 76.100\\n  libavdevice    58. 13.100 / 58. 13.100\\n  libavfilter     7.110.100 /  7.110.100\\n  libavresample   4.  0.  0 /  4.  0.  0\\n  libswscale      5.  9.100 /  5.  9.100\\n  libswresample   3.  9.100 /  3.  9.100\\n  libpostproc    55.  9.100 / 55.  9.100\\n0:0: Protocol not found\\nDid you mean file:0:0?\\n'")
```
**Expected behavior**
The webcam records the video/audio and should store as "hls.m3u8".

**Local machine (please complete the following information):**
 - OS: [e.g. Mac OS]
 - FFMped [e.g. 4.4.2]

**Comment by Naveenkumar-Ragunathan** [comment]
Since I unable to create a pull request, I will add my suggestion in this comment.

**Findings:**

- The root cause for the above issue is due to the options are not properly transferred to initialisation classes.

- As per the code [here](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming/blob/master/ffmpeg_streaming/_input.py#L96-L97). The options are altered.

**Suggestions/Fix:**
- Use `get` instead of `pop`. This will be applicable to `capture` and `pre_opts`.

Kindly verify the same and add your thoughts.  Thanks in advance.

**Comment by 97pratyush** [comment]
Facing the same issue on my mac. Can't capture webcam video

**Comment by 7luka7tadic7** [comment]
It works for me when i add get instead for pop. How to add multiple representations because when I add _360p and _720p, I get error?

**Comment by aminyazdanpanah** [comment]
Thank you for the report.
I am going to refactor this library and I will consider your bug report
