### ISSUE TITLE
Copy codec for video

### ISSUE THREAD

**Issue by gsemyong** [aminyazdanpanah/python-ffmpeg-video-streaming#96]
Can you please add "copy" codec for video? Sometimes when downloading from m3u8 manifest, the video comes suitably encoded, so I would like to not transcode video additionally to save time/compute.

From what I understand, adding "copy" to codecs list for various formats (in my case it is H264) should work:

![image](https://user-images.githubusercontent.com/46911188/201471569-38aa8bc2-e403-4e6d-8fc4-7d9fe26c1f28.png)

Thanks!

**Comment by aminyazdanpanah** [comment]
Sure, I will add this value in the next release
