### ISSUE TITLE
Produce arbitrary HLS fragment files from .mp4 from an entry recorded in .m3u8 file

### ISSUE THREAD

**Issue by brunoais** [aminyazdanpanah/python-ffmpeg-video-streaming#97]
I'm preparing to make a server which provides video viewing of content I have available.

There's already a server (soon-to-be backend) with a large library of h.265 encoded .mp4 files in shingled HDD (slow).
There will be two front-end servers with small (by comparison) SSD (fast & small) "cache" storage.

Would I be able to make use of this library to only generate the master .m3u8 file and then get arbitrary excepts of those files without loading them fully?

# Example
E.g. (values taken from examples in https://video.aminyazdanpanah.com/python/start)

## Files available
Only `3` files exist (the first two generated using this library on the 3rd file):

master `.m3u8` file:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=684032,RESOLUTION=640x360
amin_360p.m3u8
```
`amin_360p.m3u8` file:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:11.200000,
amin_360p_0000.ts
#EXTINF:9.600000,
amin_360p_0001.ts
#EXTINF:9.600000,
amin_360p_0002.ts
#EXTINF:9.600000,
amin_360p_0003.ts
#EXTINF:11.200000,
amin_360p_0004.ts
#EXTINF:1.133333,
amin_360p_0005.ts
#EXT-X-ENDLIST
```
`amin_360p.mp4` file.

## Scenario
My program receives a request to provide `amin_360p_0004.ts`. Assuming it's not in case, it will request the file from the backend.

#### Here is where the library would be extra useful, I can't find in the manual
Ideally, I could just use this library to splice `amin_360p_0004.ts` out of `amin_360p.mp4` and stream that fragment directly (or just store into a python variable) (writing only to RAM) to the cache server that requested it. (do note most videos produce thousands of fragments)

If it possible to do such action with this library? I know ffmpeg allows cutting video by the keyframe and also supports seeking in files but I don't know if there are ways to retrieve data and store it in an `.m3u8` file so the requested fragments are obtained without unwanted video+audio content.

Thank you in advance

**Comment by aminyazdanpanah** [comment]
unfortunately no. but you can use FFmpeg and [this library](https://github.com/globocom/m3u8) to accomplish your scenario.

**Comment by brunoais** [comment]
OK! Thank you.
